title: Documentation for asciidoctor-html
short_title: asciidoctor-html docs
author: Ravi Rajani
date: "10 July 2025"

chapters:
  - index.adoc
  - typography.adoc
  - numbered-environments.adoc
  - referencing.adoc

appendices:
  - tests.adoc

srcdir: .
outdir: ../html

se_id: b5711c050271f4ccc
