title: Documentation for Asciidoctor::Html
short_title: Asciidoctor::Html Docs
author: Ravi Rajani
date: 10 July 2025

chapters:
  - index.adoc
  - typography.adoc
  - numbered-environments.adoc
  - referencing.adoc

appendices:
  - asciidoc.adoc

srcdir: .
outdir: www
