= Getting Started
:sectnumlevels: 2
:description: Instructions on how to configure and start using the \
static site generator asciidoctor-html. Describes a quick start GitHub \
publishing workflow as well as a Ruby-based local toolchain.

include::includes/variables.adoc[]

NOTE: Most users will prefer the <<sec-advanced-usage>> over the <<sec-quick-start>>.

[#sec-quick-start]
== Quick Start

. Create a new repository from the public {template-repo}.
. Modify the `index.adoc` file to include your custom content for the landing page.
. Create AsciiDoc files for additional pages or for includes to be shared among pages.
. Modify the `config.yml` file. List additional pages under `chapters` or `appendices` as appropriate.
. Under your repository's bi:gear[] Settings, navigate to the Pages tab, and enable *GitHub Actions*
  as your Build and Deployment Source.
. Commit and push your changes. The site will get built and deployed on GitHub's servers.

[#sec-advanced-usage]
== Advanced Usage

.Prerequisite
[CAUTION]
You have https://www.ruby-lang.org/en/documentation/installation/[Ruby]
and https://nodejs.org/[node.js] installed on your system.

:sectnums:

=== Create a repo

The best way to create a repo is to clone the {template-repo}.
If you prefer to start from a clean repo, then you
will have to modify and supplement the steps below accordingly.

=== Install gems

In the root directory, run

[source,bash]
----
gem install bundler <1>
bundle install      <2>
----
<1> Skip this if you already have https://bundler.io/[Bundler] installed.
<2> Installs the required Ruby dependencies.

=== Install NPM packages

These are needed to create an optimised build and to enable fast live previews.

[source,bash]
----
npm i
----

=== Build and preview the site

Open a terminal window and, in the AsciiDoc sources directory, run

[source,bash]
----
adoctohtml --watch <1>
----
<1> Builds an HTML site in the `public` directory, automatically
regenerating the output when an AsciiDoc source is modified. The output directory
can be changed in the <<config-yaml,configuration file>>.

In another terminal, run

[source,bash]
----
npm start <1>
----
<1> This starts a live preview server on `localhost:3000`.

WARNING: The `adoctohtml` script only listens to changes to the source files listed under `chapters` and `appendices`
in <<config-yaml>>. If you change the configuration file itself, or any includes or <<sec-assets,assets>>,
you will need to restart the script to see the effect of your changes.

:!sectnums:

[#sec-configuration]
== Configuration

The `adoctohtml` script loads its configuration from a file whose location can be specified on the command line.

****
.`adoctohtml [options]`
[title-prefix=Usage]
`-w, --watch`::
Watch for file changes in `srcdir`.
`-b, --bust-cache`::
Rename assets in `outdir` to force browsers to fetch new versions.
`-c, --config-file CONFIG`::
Location of config file. Default: `config.yml`.
`-v, --version`::
Print the version number and exit.
****

The available configuration options are shown in the {docs-yaml}[config.yml] for this
documentation site which we reproduce below.

.config.yml
[source#config-yaml.monotitle,yaml]
----
include::config.yml[]
----

[#sec-latex]
== LaTeX

You can insert inline LaTeX code within single `{dollar}` signs or using the inline `stem`
macro. Displaymath code can be inserted within `\[` and `\]` delimiters or inside
a passthrough block with the `stem` style.

TIP: If you want to display a dollar sign, use the `\{dollar}` variable.

[#sec-nav]
== Navigation Menus and Submenus

{asciidoctor-html} will automatically generate a navigation menu if the site
contains multiple pages. Furthermore, a navigation submenu will be displayed below the
active navigation item provided the active page contains multiple level 1 (`==`) sections
*with an ID attribute*.

TIP: You can prevent a section with an ID appearing in a navigation submenu with the `skipnav`
option on a section.

[#sec-assets]
== Assets

Images should be added to the folder `{dollar}srcdir/assets/img` and referred to in the AsciiDoc sources
by just the name of the file.

Subfolders `img`, `css`, `favicon` of `{dollar}srcdir/assets` will get copied over to `{dollar}outdir`. You may use
this feature to replace the {default-assets}[default assets] included with {asciidoctor-html}.
