= Ordered Lists
:description: asciidoctor-html has many useful features for ordered lists that include \
automatic generation of reference text and support for pseudocode, bibliographies, and \
lists of figures. These features are demonstrated by means of \
an example of typesetting an exercise from a textbook in theoretical computer science.

include::includes/variables.adoc[]

{asciidoctor-html} provides some additional features for https://docs.asciidoctor.org/asciidoc/latest/lists/ordered/[ordered lists], including automatic generation of reference text.

[#sec-basic-list]
== Basic List

The default ordered list looks like <<ex-basic-list>>.

[#ex-basic-list]
.Basic list with 4 levels
====
. A level 1 list item, marked with an arabic numeral followed by a dot.
. Another level 1 list item.
.. [[li-level2]]A level 2 list item, marked with a bracketed lowercase letter.
... A level 3 list item, marked with a lowercase roman numeral followed by a dot.
.... A level 4 list item, marked with a bracketed uppercase letter.
.... [[li-level4]]Another level 4 list item.
... Another level 3 list item.
.. Another level 2 list item.
====

If you put an anchor at the start of a list item, then you will
be able to refer to that list item elsewhere in the text. This is already
possible with {asciidoctor-org} but requires explicit specification of reference text. By contrast,
{asciidoctor-html} will automatically substitute appropriate default reference text when it is unspecified. For example,
putting the anchor `\[[li-level2]]` at the start of the first level 2 list item in <<ex-basic-list>> will generate
the reference link <<li-level2>> with `\<<li-level2>>`.
In a similar way, you can generate the link <<li-level4>> to the second level 4 list item.

[#sec-continue]
== Continue Attribute

If you want to define a list that is a continuation of a list defined elsewhere
(usually appearing before it), you should use the `continue` attribute, set to the
ID of the other list.

[#ex-continue]
.Continuing a list
====
[#lst-first]
. A level 1 list item of a list with ID `lst-first`.
. Another level 1 list item.
.. A level 2 list item.
... A level 3 list item.
... Another level 3 list item.
.. Another level 2 list item.

The list below is a continuation of the above list,
achieved with `[continue=lst-first]`.

[continue=lst-first]
. This is the next level 1 item of the list with ID `lst-first`.
. Another level 1 item.
====

WARNING: Lists in AsciiDoc also accept a `start` attribute, with which you can
start the list at any desired number. There is almost *never* a good reason to do
this. In most cases you will want to use the `continue` attribute instead. It is always
best to leave the numbering to the system rather than trying to maintain it yourself.

[#sec-markers]
== Markers Attribute

You can change the type of marker used at any list level with the `markers` attribute.
This attribute accepts a format string of the form `{dollar}left-delimiter{dollar}numeral{dollar}right-delimiter`
where `{dollar}numeral` must be a single character from the string `1iIaA`. These characters represent arabic numerals,
lower or uppercase roman numerals, and lower or uppercase letters. The left and right delimiters may be arbitrary
characters and do not have to be present.

For example, setting `[markers=#1]` on the first level, `[markers=(I)]`
on the second level, and `[markers=i)]` on the third, gives <<ex-markers>>.

[#ex-markers]
.List with custom markers
====
[markers=#1]
. A level 1 list item, marked with a number preceded by a hash.
. Another level 1 list item.
[markers=(I)]
.. A level 2 list item, marked with an uppercase roman numeral enclosed in brackets.
[markers=i)]
... A level 3 list item, marked with a lowercase roman numeral followed by a bracket.
... Another level 3 list item.
.. [[li-lvl2-alt]]Another level 2 list item.
====

Again, reference text gets resolved properly. E.g., <<li-lvl2-alt>>.

[#sec-pseudocode]
== Pseudocode Style

You can make all levels of a list share the same counter (and marker) by declaring
the `pseudocode` style on the top level. The markers will all be aligned as in <<ex-pseudocode>>.

[#ex-pseudocode]
.Pseudocode list
====
[pseudocode#lst-pseudocode]
. A level 1 item of a pseudocode list.
. Another level 1 list item.
.. A level 2 item will be indented.
... And a level 3 item will be indented more.
.. Another level 2 list item.

The pseudocode list below is a continuation of the above,
achieved with the `continue` attribute.

[pseudocode,continue=lst-pseudocode]
. Continuing the pseudocode list.
.. Yet another level 2 list item.
====

[#sec-bibliography]
== Bibiliography Style
Setting a list's style to `bibliography` will render the markers as arabic numerals in square brackets.
When clicking on a generated reference link to a bibliography item, such as <<bib-roughgarden>>,
the citation will appear in a popover. If you specify reference text in a bibliography citation, it will appear
next to the generated number as in <<bib-roughgarden,p.10>>.

[#ex-bibliography]
.Bibliography list
====
[bibliography]
. [[bib-cormen]]Cormen, T.H. et al. (2022) Introduction to Algorithms. Cambridge, MA: The Mit Press.
. [[bib-roughgarden]]Roughgarden, T. (2022) Algorithms Illuminated: Omnibus Edition. Cambridge: CUP.
====

TIP: Since citations appear in popovers, you may wish not to show the bibliography on the page.
You can hide any block by giving it the `hidden` role.

[#sec-real-example]
== Real Example

In this section, we reproduce an exercise from <<bib-cormen,p.46>>. It demonstrates all the list
features introduced thus far in the context of a "`real`" example.

[algorithm#alg-bubblesort]
.text:sc[BubbleSort]$(A,n)$
====
This procedure sorts array $A[1:n]$.

[pseudocode]
. [[line-outer-for]]*for* $i=1$ *to* $n-1$
.. [[line-inner-for]]*for* $j=n$ *downto* $i+1$
... *if* $A[j] < A[j-1]$
.... [[line-statement]]swap $A[j]$ with $A[j-1]$
====

In the following exercise, the correctness of <<alg-bubblesort>> is proved.

[exercise]
.Correctness of <<alg-bubblesort,text:sc[BubbleSort]>>
====
Bubblesort is a popular, but inefficient, sorting algorithm.
It works by repeatedly swapping adjacent elements that are out of order.

[#lst-exercise-parts%roomy,markers=(a)]
. Let $A'$ denote the array $A$ after text:sc[BubbleSort]$(A,n)$ is executed.
To prove that text:sc[BubbleSort] is correct, you need to prove that it terminates and that
+
[stem#bs-inequality%numbered]
++++
A'[1] \leq A'[2] \leq \dots \leq A'[n]
++++
+
In order to show that text:sc[BubbleSort] actually sorts, what else do you need to prove?

The next two parts prove inequality <<bs-inequality>>.

[%roomy,continue=lst-exercise-parts,markers=(a)]
. [[bs-loop-invariant]]State precisely a loop invariant for the for loop in lines <<line-inner-for>>-<<line-statement>>,
and prove that this loop invariant holds.
Your proof should use the structure of the loop-invariant proof presented in <<bib-cormen,ch.2>>.
. Using the termination condition of the loop invariant proved in part <<bs-loop-invariant>>, state
a loop invariant for the for loop in lines <<line-outer-for>>-<<line-statement>> that allows you to prove inequality <<bs-inequality>>.
Your proof should use the structure of the loop-invariant proof presented in <<bib-cormen,ch.2>>.
. What is the worst-case running time of text:sc[BubbleSort]? How does it compare
with the running time of text:sc[InsertionSort]?
====

TIP: Use the `roomy` option if you want some extra space between list items.

[#sec-figlist]
== List of Figures

One often wants to display two images as subfigures of one figure with automatic label numbers.
You can do this easily by declaring the `figlist` style on an ordered list, and
putting an inline image in each list item. The list title will get rendered as
an overall caption, and each image's title attribute will get
rendered as a subcaption.

[figlist#fig-changepoint-mcmc]
.Marginal posteriors of Poisson parameters in change point detection of UK coal mining disasters. Computed by Gibbs algorithm with $B = G = 1000$.
. image:gb73b.svg[Posterior theta1,title=Posterior distribution of first Poisson parameter $\theta_1$.]
. [[fig-posterior-theta2]]image:gb73c.svg[Posterior theta2,title=Posterior distribution of second Poisson parameter $\theta_2$ after change point.]

Again, reference text is properly resolved. Just look at <<fig-posterior-theta2>>.

