= Ordered Lists
:description: asciidoctor-html has many useful features for ordered lists that include \
automatic generation of reference text and support for pseudocode, bibliographies, and \
lists of figures. These features are demonstrated by means of \
an example of typesetting an exercise from a textbook in theoretical computer science.

include::includes/variables.adoc[]

{asciidoctor-html} provides some additional features for https://docs.asciidoctor.org/asciidoc/latest/lists/ordered/[ordered lists], including automatic generation of reference text.

[#sec-basic-list]
== Basic List

The default ordered list looks like <<ex-basic-list>>.

[#ex-basic-list]
.Basic list with 4 levels
====
. Level 1 list item, marked with an arabic numeral followed by a dot.
. Another level 1 list item.
.. [[li-level2]]A level 2 list item, marked with a bracketed lowercase letter.
... A level 3 list item, marked with a lowercase roman numeral followed by a dot.
.... A level 4 list item, marked with a bracketed uppercase letter.
.... [[li-level4]]Another level 4 list item.
... Another level 3 list item.
.. Another level 2 list item.
====

If you put an anchor at the start of a list item, then you will
be able to refer to that list item elsewhere in the text. This is already
possible with {asciidoctor-org} but requires explicit specification of reference text. By contrast,
{asciidoctor-html} will automatically substitute appropriate default reference text when it is unspecified. For example,
putting the anchor `\[[li-level2]]` at the start of the first level 2 list item in <<ex-basic-list>> will generate
the reference link <<li-level2>> with `\<<li-level2>>`.
In a similar way, you can generate the link <<li-level4>> to the second level 4 list item.

[#sec-start-shift]
== Start and Shift Attributes

As with {asciidoctor-org}, you can choost to start any of the levels at a different "`number`" with the `start`
attribute.
For example, with <<ex-basic-list>>, using `[start=3]` on the first level and `[start=4]` on the second level,
gives <<ex-start>>.

[#ex-start]
.List with start attributes
====
[start=3]
. Level 1 list item, marked with an arabic numeral followed by a dot.
. Another level 1 list item.
[start=4]
.. A level 2 list item, marked with a bracketed lowercase letter.
... A level 3 list item, marked with a lowercase roman numeral followed by a dot.
.... A level 4 list item, marked with a bracketed uppercase letter.
.... Another level 4 list item.
... Another level 3 list item.
.. Another level 2 list item.
====

You can also change the type of marker used at any list level with the `shift` attribute.
For example, setting `[shift=3]` on the first level and `[start=2,shift=-1]`
on the second level gives <<ex-shift>>.

[#ex-shift]
.List with start and shift attributes
====
[shift=3]
. Level 1 list item, marked with a bracketed uppercase letter.
. Another level 1 list item.
[start=2, shift=-1]
.. A level 2 list item, marked with an arabic numeral followed by a dot.
.. [[li-lvl2-alt]]Another level 2 list item.
====

Again, reference text gets resolved properly. E.g., <<li-lvl2-alt>>.

[#sec-pseudocode]
== Pseudocode Style

You can make all levels of a list share the same counter (and marker) by declaring
the `pseudocode` style on the top level. The markers will all be aligned as in <<ex-pseudocode>>.

[#ex-pseudocode]
.Pseudocode list
====
[pseudocode]
. Level 1 item of a pseudocode list.
. Another level 1 list item.
.. A level 2 item will be indented.
... And a level 3 item will be indented more.
.. Another level 2 list item.
====

== Bibiliography Style
Setting a list's style to `bibliography` will render the markers as arabic numerals in square brackets.
When clicking on a generated reference link to a bibliography item, such as <<bib-roughgarden>>,
the citation will appear in a popover. If you specify reference text in a bibliography citation, it will appear
next to the generated number as in <<bib-roughgarden,p.10>>.

[#ex-bibliography]
.Bibliography list
====
[bibliography]
. [[bib-cormen]]Cormen, T.H. et al. (2022) Introduction to Algorithms. Cambridge, MA: The Mit Press.
. [[bib-roughgarden]]Roughgarden, T. (2022) Algorithms Illuminated: Omnibus Edition. Cambridge: CUP.
====

TIP: Since citations appear in popovers, you may wish not to show the bibliography on the page.
You can hide any block by giving it the `hidden` role.

[#sec-real-example]
== Real Example

In this section, we reproduce an exercise from <<bib-cormen,p.46>>. It demonstrates all the list
features introduced thus far in the context of a "`real`" example.

[algorithm#alg-bubblesort]
.sc:[BubbleSort]$(A,n)$
====
This procedure sorts array $A[1:n]$.

[pseudocode]
. [[line-outer-for]]*for* $i=1$ *to* $n-1$
.. [[line-inner-for]]*for* $j=n$ *downto* $i+1$
... *if* $A[j] < A[j-1]$
.... [[line-statement]]swap $A[j]$ with $A[j-1]$
====

In the following exercise, the correctness of <<alg-bubblesort>> is proved.

[exercise]
.Correctness of <<alg-bubblesort,sc:[BubbleSort]>>
====
Bubblesort is a popular, but inefficient, sorting algorithm.
It works by repeatedly swapping adjacent elements that are out of order.

[shift=1]
. Let $A'$ denote the array $A$ after sc:[BubbleSort]$(A,n)$ is executed.
To prove that sc:[BubbleSort] is correct, you need to prove that it terminates and that
+
[stem#bs-inequality%numbered]
++++
A'[1] \leq A'[2] \leq \dots \leq A'[n]
++++
+
In order to show that sc:[BubbleSort] actually sorts, what else do you need to prove?

The next two parts prove inequality <<bs-inequality>>.

[start=2,shift=1]
. [[bs-loop-invariant]]State precisely a loop invariant for the for loop in lines <<line-inner-for>>-<<line-statement>>,
and prove that this loop invariant holds.
Your proof should use the structure of the loop-invariant proof presented in <<bib-cormen,ch.2>>.
. Using the termination condition of the loop invariant proved in part <<bs-loop-invariant>>, state
a loop invariant for the for loop in lines <<line-outer-for>>-<<line-statement>> that allows you to prove inequality <<bs-inequality>>.
Your proof should use the structure of the loop-invariant proof presented in <<bib-cormen,ch.2>>.
. What is the worst-case running time of sc:[BubbleSort]? How does it compare
with the running time of sc:[InsertionSort]?
====

[#sec-figlist]
== List of Figures

One often wants to display two images as subfigures of one figure with automatic label numbers.
You can do this easily by declaring the `figlist` style on an ordered list, and
putting an inline image in each list item. The list title will get rendered as
an overall caption, and each image's title attribute will get
rendered as a subcaption.

[figlist#fig-changepoint-mcmc]
.Marginal posteriors of Poisson parameters in change point detection of UK coal mining disasters. Computed by Gibbs algorithm with $B = G = 1000$.
. image:gb73b.svg[Posterior theta1,title=Posterior distribution of first Poisson parameter $\theta_1$.]
. [[fig-posterior-theta2]]image:gb73c.svg[Posterior theta2,title=Posterior distribution of second Poisson parameter $\theta_2$ after change point.]

Again, reference text is properly resolved. Just look at <<fig-posterior-theta2>>.

