= Macros
:description: Useful macros are included with asciidoctor-html that allow for: proper \
cross referencing of content on other pages with full resolution of reference text; \
footnotes that are rendered in popovers; easy insertion of icons; and rendering of \
semantic inline text elements.

include::includes/variables.adoc[]

{asciidoctor-html} includes some convenient inline macros
in addition to those made available by {asciidoctor-org}.

[#sec-cref]
== cref

The `cref` inline macro allows you to cross reference blocks or anchors in other pages.
Reference text gets properly resolved if unspecified.

****
[title-prefix=Usage]
.pass:q,a[`cref:{dollar}docname{dollar}anchor[{dollar}reftext\]`]
docname:: The name of the AsciiDoc file. The `.adoc` extension may be omitted.
anchor:: (Optional) The ID of the element referenced in `{dollar}docname` preceded by a `#`.
reftext:: (Optional) The reference text to be used if the default resolution is not suitable. 
****

.Example uses of the cref macro
[%compact]
|===
|Source |Generated Link

|pass:q[`cref:index[\]`] |cref:index[]
|pass:q[`cref:lists[\]`] |cref:lists[]
|pass:q[`cref:lists[Ordered Lists\]`] |cref:lists[Ordered Lists]
|pass:q[`cref:numbered-blocks#tbl-reference[Reference Table\]`] |cref:numbered-blocks#tbl-reference[Reference Table]
|pass:q[`cref:numbered-blocks#lem-monotone-likelihood[\]`] |cref:numbered-blocks#lem-monotone-likelihood[]
|pass:q[`cref:tests[\]`]
|cref:tests[]
|===

[#sec-footnote]
== footnote
:fn-demo: pass:q,a[footnote:[ \
*Syntax:* `footnote:[{dollar}content\]`{parskip} \
Content can include LaTeX such as \[x + 1 = 2 \Rightarrow x = 1\\] \
]] 

The footnote macro is included in {asciidoctor-org}. However, instead of creating a link to a footnote
at the bottom of the page, {asciidoctor-html} shows the footnote in a
popover.{fn-demo}

TIP: Use the `\{parskip}` variable to force an appropriate vertical space inside a
footnote. Insert the variable directly following the preceding text (with no spaces).
This variable can also be useful inside list items.

[#sec-bi]
== bi

You can insert any icon from {bs-icons} with the `bi` macro.

****
[title-prefix=Usage]
.pass:q,a[`bi:{dollar}name[{dollar}font-size,{dollar}color\]`]
name:: Any of the icon names listed https://icons.getbootstrap.com/#icons[here].
font-size:: (Optional) A percentage value relative to the surrounding font.
color:: (Optional) A https://developer.mozilla.org/en-US/docs/Web/CSS/color_value[color value].
****

.Example uses of the bi macro
[%compact,valign=middle]
|===
|Source |Generated Icon

|pass:q[`bi:arrow-through-heart[\]`] |bi:arrow-through-heart[]
|pass:q[`bi:bicycle[130%\]`] |bi:bicycle[130%]
|pass:q[`bi:balloon-fill[100%,magenta\]`] |bi:balloon-fill[100%,magenta]
|===

[#sec-text]
== text

Bootstrap's semantic https://getbootstrap.com/docs/5.3/content/typography/#inline-text-elements[inline text elements]
are supported via the `text` macro.

****
[title-prefix=Usage]
.pass:q,a[`text:{dollar}style[{dollar}text,{dollar}attrs&hellip;\]`]
style:: The type of formatting to be applied.
text:: The text to apply the formatting to.
attrs:: When `{dollar}style=abbr`, supply a hover `title` and optional `role=initialism` for
slightly smaller uppercase text.
****

NOTE: _These_ types of #markup# are built in to the *AsciiDoc* language and _don't_ require the
`text` macro.

.Example uses of the text macro
[%compact]
|===
|Source |Generated Text

|pass:q[`text:del[deleted text\]`] |text:del[deleted text]
|pass:q[`text:strike[no longer accurate\]`] |text:strike[no longer accurate]
|pass:q[`text:ins[an addition\]`] |text:ins[an addition]
|pass:q[`text:underline[underlined text\]`] |text:underline[underlined text]
|pass:q[`text:small[fine print\]`] |text:small[fine print]
|pass:q[`text:sc[SmallCaps\]`] |text:sc[SmallCaps]
|pass:q[`text:muted[faint text\]`] |text:muted[faint text]
|pass:q[`text:danger[a warning\]`] |text:danger[a warning]
|pass:q[`text:abbr[attr,title=attribute\]`] |text:abbr[attr,title=attribute]

|pass:q[`text:abbr[HTML,title=HyperText Markup Language,role=initialism\]`]
|text:abbr[HTML,title=HyperText Markup Language,role=initialism]

|pass:q[`text:kbd[Ctrl + A\]`] |text:kbd[Ctrl + A]
|===
