= Presentations
:description: asciidoctor-html features an easy to use presentation mode \
for presenting lecture slides using the same tool used for writing the lecture notes.

:pagestyle: presentation

include::includes/variables.adoc[]

[.vcenter]
{asciidoctor-html} has a presentation mode in which a chapter is displayed as a slide deck.
To render a chapter in presentation mode by default, use the document property
`:pagestyle: presentation`.

[#sec-outline%skipnav]
== Outline

subnav::[live=normal-faded]

[#sec-multicolumn]
== [.text-nowrap]#Multi-Column Layout#

[%roomy]
* A section with an ID attribute starts a new slide.
* A subsequent section without an ID is displayed in a new column to the right if the screen is large enough.

== {notitle}

[TIP.mt-0]
====
Use the `{notitle\}` variable in the section heading if you do not want to display a separate title
for a column.
====

[#sec-live-attribute]
== Live Attribute

Any source code, (un)ordered list, table, description list, or cref:macros#sec-subnav[] block supports a `live` attribute which allows the presenter to step through
the "`lines`". The attribute value is of the form `{dollar}initial-{dollar}live` where `{dollar}initial` is one of
`normal`, `faded` or `covered`, and `{dollar}live` is one of `faded` or `covered`.

For example, the list in the right column has `live=covered-covered`. Repeatedly press the text:kbd[n] button to
uncover each line one at a time.

== Covered List Demo

[live=covered-covered]
* You just uncovered me with the text:kbd[n] (for __**n**__ext) key!
* Now try uncovering the next line by pressing text:kbd[3].
* You can toggle any line by pressing the numeric key corresponding to its line number.
E.g., try pressing text:kbd[2], and then press text:kbd[n] again.
** Uncovering works as expected with nested lists. Press text:kbd[b] a couple of times
to move __**b**__ack. Then move beyond this line with the text:kbd[n] key.
* Once you've reached the end of the list, pressing text:kbd[n] again uncovers the first line
of the next live block on the current slide, or if there is no such line, flips to the next slide.

[#sec-keyboard-navigation]
== [.text-nowrap]#Keyboard Navigation#

[%nocaption,cols="1,2"]
|===
|text:kbd[bi:arrow-left[\]] text:kbd[bi:arrow-right[\]]
|Move to the previous/next slide

|text:kbd[B] text:kbd[N]
|Move to the previous/next live block
|===

[#sec-live-demos]
== Live Code Demos

The following cref:lists#sec-pseudocode[pseudocode] list has `live=normal-faded`.

[pseudocode,live=normal-faded]
. text:sc[reverse]$(x[1:n])$:
.. *for* $i \gets 1$ *to* $\lfloor n/2\rfloor$:
... $\textit{tmp}\gets x[i]$
... $x[i]\gets x[n-i+1]$
... $x[n - i + 1]\gets \textit{tmp}$

[#sec-thank-you%skipnav]
== The End

[.lead]
Thank you bi:emoji-sunglasses[]
