= Presentations
:description: asciidoctor-html features an easy to use presentation mode \
for presenting lecture slides using the same tool used for writing the lecture notes.

:pagestyle: presentation

include::includes/variables.adoc[]

[.vcenter]
{asciidoctor-html} has a presentation mode in which a chapter is displayed as a slide deck.
To render a chapter in presentation mode by default, use the document property
`:pagestyle: presentation`.

[#sec-outline.fit-content]
== Outline

[.subnav%roomy]
. <<sec-keyboard-navigation>>
. <<sec-multicolumn>>

== {notitle}

[TIP.mt-0]
--
Use the `subnav` role on a list to style the links like a cref:macros#sec-subnav[].
--

[#sec-keyboard-navigation]
== Keyboard Navigation

[%roomy]
* Use the left/right arrow keys to navigate to the previous/next slide.
* Use the up/down arrow keys to scroll the content if it overflows vertically.
* Use the text:kbd[esc] or text:kbd[e] key to exit presentation mode and enter multipage mode.

[#sec-multicolumn]
== Multi-Column Layout

[%roomy]
* A section with an ID attribute starts a new slide.
* A subsequent section without an ID is displayed in a new column to the right if the screen is large enough.

== {notitle}

[TIP.mt-0]
====
Use the `{notitle\}` variable in the section heading if you do not want to display a separate title
for a column.

Use the `fit-content` role on a section to make its column fit the content instead of its width being
equal to the others. We did this on the first column of the <<sec-outline>> slide.
====

[#sec-thank-you]
== The End

[.lead]
Thank you bi:emoji-sunglasses[]
