AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Metrics/AbcSize:
  Max: 40

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 15

Metrics/MethodLength:
  Max: 30

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

plugins:
  - rubocop-minitest
  - rubocop-rake
