AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Metrics/AbcSize:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 25

Metrics/PerceivedComplexity:
  Max: 25

Metrics/BlockNesting:
  Max: 5

Metrics/MethodLength:
  Max: 35

Metrics/ClassLength:
  Max: 300

Metrics/ModuleLength:
  Max: 300

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

plugins:
  - rubocop-minitest
  - rubocop-rake
