#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
CSS_FILE="assets/css/jupyterlite.css"
CSS_LINK="<link rel=\"stylesheet\" href=\"../../$CSS_FILE\">"
USAGE="Usage: $(basename "$0") [-h] [-c contentdir] [-o outdir] srcdir"

outdir=www/jupyterlite
contentdir=notebooks

while getopts "c:o:h" opt; do
    case $opt in
        o)
        outdir="$(realpath "$OPTARG")"
        ;;
        c)
        contentdir="$(realpath "$OPTARG")"
        ;;
        h)
        echo "$USAGE"
        exit 0
        ;;
        ?)
        echo -e "Invalid option.\n$USAGE"
        exit 1
        ;;
    esac
done
shift "$((OPTIND-1))"
if [[ "$#" -lt 1 ]]; then
    echo -e "Missing positional argument.\n$USAGE"
    exit 1
fi
echo "Content directory: $contentdir" 
echo "Output directory: $outdir"
cd "$1"
if [[ ! -d $outdir ]]; then
    python -m pip install -r requirements.txt
fi
jupyter lite build --contents "$contentdir" --output-dir "$outdir"
sed -i "s|</head>|$CSS_LINK\n</head>|g" "$outdir/repl/index.html"
